### ISSUE TITLE
pip install errors 

### ISSUE THREAD

**Issue by rjleveque** [clawpack/doc#140]
Errors resulting from pip install, I think from f2py trying to compile Riemann solvers, but we didn't have time to debug before she left town.  After setting PYTHONPATH, things worked fine in classic and other Fortran repos.

[errors.txt](https://github.com/clawpack/doc/files/706156/errors.txt)

**Comment by mandli** [comment]
The line
```
/usr/local/lib/gcc/x86_64-apple-darwin13.1.0/4.9.0/include-fixed/stdint.h:27:32: fatal error: sys/_types/_int8_t.h: No such file or directory
```
suggests that the Fortran compiler she had was incompatible with the Python she was using as this is a very basic header that should be available.  Do you know how or what gfortran she used?

**Comment by rjleveque** [comment]
Only what's at the bottom of the errors.txt file,
 
```
$ gfortran --version
GNU Fortran (GCC) 4.9.0
Copyright (C) 2014 Free Software Foundation, Inc.
```

**Comment by mandli** [comment]
The binaries from at least the HPC site we used to point to has problems with compatibility with Python so I would hazard that this might be part of the problem.  These compilers work fine until you have to start interfacing with other system components where Apple never supported anything beyond gcc 4.2 and has now moved to clang and LLVM.  The compilers provided by `homebrew` take this into account (as does `macports`) so that things interact in a friendly way.  I am not sure if this is the problem but it would be my first guess.

**Comment by ketch** [comment]
https://github.com/clawpack/clawpack/pull/104 may provide an alternative that sidesteps all of this.

**Comment by ketch** [comment]
I'm going to close this; if we get enough information to reproduce it then we can reopen.
