### ISSUE TITLE
Keep documentation of older versions

### ISSUE THREAD

**Issue by ketch** [clawpack/doc#149]
This can be done with a sphinx extension:

https://robpol86.github.io/sphinxcontrib-versioning/index.html

Just do:

    pip install -U sphinx
    pip install sphinxcontrib-versioning
    cd $CLAW/doc
    sphinx-versioning build -r master doc doc/_build/html

This builds the docs for every tag and every branch in the doc repo.  The resulting documentation includes, on every page, a list of versions on the left side.  Clicking a version number takes you to the same doc page, but for that version.  The only catch is that this won't provide galleries for the older versions, but it seems like a step forward from what we have now.  We could manually check out older versions of clawpack and build the galleries for each version if we wanted, but it's probably not worthwhile.

**Comment by mandli** [comment]
This is great!  Crazy that this is not easier to find.

**Comment by rjleveque** [comment]
We discovered a few oddities, in particular the gallery `.rst` files that are auto-generated and not tracked by `git` aren't found by this version of sphinx, but I think we've sorted that out and I'll soon issue a PR implementing this.

**Comment by rjleveque** [comment]
Well now the `.rst` files are found, but the thumbnail images of the examples won't be unless we also commit all of those to Git, which we probably don't want to do.  In fact I think we'd have to push all the source code and plots now found e.g. under http://www.clawpack.org/_static/classic/examples/acoustics_1d_example1/README.html
in order for the galleries to show up.

So we might have keep the gallery files elsewhere and rewrite the `.rst` files generated for galleries to point to the appropriate place, rather than assuming they will be put in `_static`. For example we could change the above link to point to:
`http://www.clawpack.org/galleries/classic/examples/acoustics_1d_example1/README.html`
or even to something like:
`http://www.clawpack.org/galleries-v5.4.0/classic/examples/acoustics_1d_example1/README.html`
if we want to keep track of versions of galleries.  Whenever we update to a new version we could create a new directory `$CLAW/clawpack.github.com/galleries-v5.4.0` and make sure we point to this in `.rst` files.  Then switching to a different version would bring in sphinx pages that point to a different version of the gallery as well.  Note that we already commit all these gallery files to the clawpack/clawpack.github.com repository, https://github.com/clawpack/clawpack.github.com/tree/master/_static
so we could even reconstruct the galleries for previous versions.

If others want to experiment with this, I pushed a new branch `sphinx-versioning` since the newly committed `.rst` files have to be on a branch at `origin` in order to be seen.  

https://github.com/clawpack/doc/compare/sphinx-versioning

**Comment by ketch** [comment]
Could we use sphinx-versioning to generate docs for tagged versions, and then use regular sphinx to generate docs for master (without destroying the ones created by sphinx-versioning)?  It seems like that way we'd have a gallery for master without having to commit all the generated files.

Another thought: the docs for old versions should never change again, right?  So maybe we just generate them all once and add them to clawpack.github.com, and then proceed as we were before?

I'd really like to avoid committing lots of generated things if we can.

**Comment by ketch** [comment]
This is done.  Closing.
